pipeline {
    agent any

    environment {
        DOCKER_HUB_REPO = 'nizzzy/docker-portfolio'
    }
    parameters{
        string(name: 'BRANCH_NAME', defaultValue: 'main', description: 'Branch to build')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${params.BRANCH_NAME}", url: 'https://github.com/Oreva-J/Jenkins-portfolio.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_HUB_REPO}:${BUILD_NUMBER}")
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-pass', url: 'https://index.docker.io/v1/']) {
                    script {
                        docker.image("${DOCKER_HUB_REPO}:${BUILD_NUMBER}").push()
                        docker.image("${DOCKER_HUB_REPO}:${BUILD_NUMBER}").push("latest")
                    }
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                script {
                    sshagent(['aws-ec2-ssh']) {
                        sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@18.203.237.67 "
                        docker pull ${DOCKER_HUB_REPO}:${BUILD_NUMBER} &&
                        docker stop portfolio || true &&
                        docker rm portfolio || true &&
                        docker run -d --name portfolio -p 80:80 ${DOCKER_HUB_REPO}:${BUILD_NUMBER}"
                        """
                    }
                }
            }
}
    }
}
